/* Generated By:JavaCC: Do not edit this line. LuaParserConstants.java */
package org.luaj.vm2.parser


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface LuaParserConstants {
    companion object {

        /** End of File.  */
        const val EOF = 0
        /** RegularExpression Id.  */
        const val COMMENT = 17
        /** RegularExpression Id.  */
        const val LONGCOMMENT0 = 18
        /** RegularExpression Id.  */
        const val LONGCOMMENT1 = 19
        /** RegularExpression Id.  */
        const val LONGCOMMENT2 = 20
        /** RegularExpression Id.  */
        const val LONGCOMMENT3 = 21
        /** RegularExpression Id.  */
        const val LONGCOMMENTN = 22
        /** RegularExpression Id.  */
        const val LONGSTRING0 = 23
        /** RegularExpression Id.  */
        const val LONGSTRING1 = 24
        /** RegularExpression Id.  */
        const val LONGSTRING2 = 25
        /** RegularExpression Id.  */
        const val LONGSTRING3 = 26
        /** RegularExpression Id.  */
        const val LONGSTRINGN = 27
        /** RegularExpression Id.  */
        const val AND = 29
        /** RegularExpression Id.  */
        const val BREAK = 30
        /** RegularExpression Id.  */
        const val DO = 31
        /** RegularExpression Id.  */
        const val ELSE = 32
        /** RegularExpression Id.  */
        const val ELSEIF = 33
        /** RegularExpression Id.  */
        const val END = 34
        /** RegularExpression Id.  */
        const val FALSE = 35
        /** RegularExpression Id.  */
        const val FOR = 36
        /** RegularExpression Id.  */
        const val FUNCTION = 37
        /** RegularExpression Id.  */
        const val GOTO = 38
        /** RegularExpression Id.  */
        const val IF = 39
        /** RegularExpression Id.  */
        const val IN = 40
        /** RegularExpression Id.  */
        const val LOCAL = 41
        /** RegularExpression Id.  */
        const val NIL = 42
        /** RegularExpression Id.  */
        const val NOT = 43
        /** RegularExpression Id.  */
        const val OR = 44
        /** RegularExpression Id.  */
        const val RETURN = 45
        /** RegularExpression Id.  */
        const val REPEAT = 46
        /** RegularExpression Id.  */
        const val THEN = 47
        /** RegularExpression Id.  */
        const val TRUE = 48
        /** RegularExpression Id.  */
        const val UNTIL = 49
        /** RegularExpression Id.  */
        const val WHILE = 50
        /** RegularExpression Id.  */
        const val NAME = 51
        /** RegularExpression Id.  */
        const val NUMBER = 52
        /** RegularExpression Id.  */
        const val FLOAT = 53
        /** RegularExpression Id.  */
        const val FNUM = 54
        /** RegularExpression Id.  */
        const val DIGIT = 55
        /** RegularExpression Id.  */
        const val EXP = 56
        /** RegularExpression Id.  */
        const val HEX = 57
        /** RegularExpression Id.  */
        const val HEXNUM = 58
        /** RegularExpression Id.  */
        const val HEXDIGIT = 59
        /** RegularExpression Id.  */
        const val HEXEXP = 60
        /** RegularExpression Id.  */
        const val STRING = 61
        /** RegularExpression Id.  */
        const val CHARSTRING = 62
        /** RegularExpression Id.  */
        const val QUOTED = 63
        /** RegularExpression Id.  */
        const val DECIMAL = 64
        /** RegularExpression Id.  */
        const val DBCOLON = 65
        /** RegularExpression Id.  */
        const val UNICODE = 66
        /** RegularExpression Id.  */
        const val CHAR = 67
        /** RegularExpression Id.  */
        const val LF = 68

        /** Lexical state.  */
        const val DEFAULT = 0
        /** Lexical state.  */
        const val IN_COMMENT = 1
        /** Lexical state.  */
        const val IN_LC0 = 2
        /** Lexical state.  */
        const val IN_LC1 = 3
        /** Lexical state.  */
        const val IN_LC2 = 4
        /** Lexical state.  */
        const val IN_LC3 = 5
        /** Lexical state.  */
        const val IN_LCN = 6
        /** Lexical state.  */
        const val IN_LS0 = 7
        /** Lexical state.  */
        const val IN_LS1 = 8
        /** Lexical state.  */
        const val IN_LS2 = 9
        /** Lexical state.  */
        const val IN_LS3 = 10
        /** Lexical state.  */
        const val IN_LSN = 11

        /** Literal token values.  */
        val tokenImage = arrayOf(
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"--[[\"",
            "\"--[=[\"",
            "\"--[==[\"",
            "\"--[===[\"",
            "<token of kind 10>",
            "\"[[\"",
            "\"[=[\"",
            "\"[==[\"",
            "\"[===[\"",
            "<token of kind 15>",
            "\"--\"",
            "<COMMENT>",
            "\"]]\"",
            "\"]=]\"",
            "\"]==]\"",
            "\"]===]\"",
            "<LONGCOMMENTN>",
            "\"]]\"",
            "\"]=]\"",
            "\"]==]\"",
            "\"]===]\"",
            "<LONGSTRINGN>",
            "<token of kind 28>",
            "\"and\"",
            "\"break\"",
            "\"do\"",
            "\"else\"",
            "\"elseif\"",
            "\"end\"",
            "\"false\"",
            "\"for\"",
            "\"function\"",
            "\"goto\"",
            "\"if\"",
            "\"in\"",
            "\"local\"",
            "\"nil\"",
            "\"not\"",
            "\"or\"",
            "\"return\"",
            "\"repeat\"",
            "\"then\"",
            "\"true\"",
            "\"until\"",
            "\"while\"",
            "<NAME>",
            "<NUMBER>",
            "<FLOAT>",
            "<FNUM>",
            "<DIGIT>",
            "<EXP>",
            "<HEX>",
            "<HEXNUM>",
            "<HEXDIGIT>",
            "<HEXEXP>",
            "<STRING>",
            "<CHARSTRING>",
            "<QUOTED>",
            "<DECIMAL>",
            "\"::\"",
            "<UNICODE>",
            "<CHAR>",
            "<LF>",
            "\"#\"",
            "\";\"",
            "\"=\"",
            "\",\"",
            "\".\"",
            "\":\"",
            "\"(\"",
            "\")\"",
            "\"[\"",
            "\"]\"",
            "\"...\"",
            "\"{\"",
            "\"}\"",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"/\"",
            "\"^\"",
            "\"%\"",
            "\"..\"",
            "\"<\"",
            "\"<=\"",
            "\">\"",
            "\">=\"",
            "\"==\"",
            "\"~=\""
        )
    }

}
