package com.soywiz.korge.gradle

enum class GameCategory {
    ACTION, ADVENTURE, ARCADE, BOARD, CARD,
    CASINO, DICE, EDUCATIONAL, FAMILY, KIDS,
    MUSIC, PUZZLE, RACING, ROLE_PLAYING, SIMULATION,
    SPORTS, STRATEGY, TRIVIA, WORD
}
