#!/usr/bin/env sh
./gradlew --stop
./gradlew --no-daemon -Dkotlin.native.disableCompilerDaemon=true -Dorg.gradle.debug=true -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.parallel=false $*
