<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.1" name="Terrain (32x32)" tilewidth="32" tileheight="32" tilecount="247" columns="19">
 <image source="Terrain (32x32).png" width="608" height="416"/>
 <tile id="20" type="collision"/>
 <tile id="21" type="collision"/>
 <tile id="22" type="collision"/>
 <tile id="24" type="collision"/>
 <tile id="26" type="collision"/>
 <tile id="27" type="collision"/>
 <tile id="29" type="collision"/>
 <tile id="30" type="collision"/>
 <tile id="32" type="collision"/>
 <tile id="33" type="collision"/>
 <tile id="35" type="collision"/>
 <tile id="39" type="collision"/>
 <tile id="41" type="collision"/>
 <tile id="43" type="collision"/>
 <tile id="45" type="collision"/>
 <tile id="46" type="collision"/>
 <tile id="48" type="collision"/>
 <tile id="49" type="collision"/>
 <tile id="51" type="collision"/>
 <tile id="52" type="collision"/>
 <tile id="54" type="collision"/>
 <tile id="55" type="collision"/>
 <tile id="58" type="collision"/>
 <tile id="59" type="collision"/>
 <tile id="60" type="collision"/>
 <tile id="62" type="collision"/>
 <tile id="83" type="collision"/>
 <tile id="84" type="collision"/>
 <tile id="86" type="collision"/>
 <tile id="87" type="collision"/>
 <tile id="89" type="collision"/>
 <tile id="90" type="collision"/>
 <tile id="92" type="collision"/>
 <tile id="93" type="collision"/>
 <tile id="96" type="collision"/>
 <tile id="97" type="collision"/>
 <tile id="98" type="collision"/>
 <tile id="100" type="collision"/>
 <tile id="102" type="collision"/>
 <tile id="103" type="collision"/>
 <tile id="105" type="collision"/>
 <tile id="106" type="collision"/>
 <tile id="108" type="collision"/>
 <tile id="109" type="collision"/>
 <tile id="111" type="collision"/>
 <tile id="112" type="collision"/>
</tileset>
